### ISSUE TITLE
Tokenizing a property declaration with a space after property name resolves incorrectly to `RuleSet` instead of `Declaration`

### ISSUE THREAD

**Issue by ergunsh** [lezer-parser/css#11]
Hey @marijnh,

It seems like when there is a space betwen the property name and the colon, the tokenizing fails; see the following case:
```
div {
    color: blue;
    color : red;
}
```

`color: blue` resolves correctly to `Declaration`; however `color : red` resolves to `RuleSet`.

I have created a tree visualizer for `@lezer/css` and `@lezer/javascript`; you can take a look here as well: https://ergun.sh/lezer-viz.html?language=%40lezer%2Fcss&sourceText=*+%7B%0A++color%3A+red%3B%0A++color+%3A+blue%3B%0A%7D

**Comment by marijnh** [comment]
This patch should help. It was getting confused because (since it supports nested rules) it was interpreting that colon as indicating some selector like `p :pseudoclass` was coming.

**Comment by ergunsh** [comment]
Ah perfect, thanks for the quick patch again! :)

Do you have a time when the fix would be published?

**Comment by marijnh** [comment]
I've tagged this in @lezer/css 1.1.7
