### ISSUE TITLE
10px10px incorrectly parsed as two tokens

### ISSUE THREAD

**Issue by pfaffe** [lezer-parser/css#12]
For example in `margin: 10px10px`, the value is incorrectly parsed as two separate tokens, where the result should be a single token (and the declaration should be invalid).

https://www.w3.org/TR/css-syntax-3/#consume-declaration
https://www.w3.org/TR/css-syntax-3/#consume-component-value

**Comment by ergunsh** [comment]
Hey @marijnh, do you have any suggestions for this? We're slowly migrating to use lezer parser for rendering property declarations in the Styles pane in DevTools (crrev.com/c/5046552) and this is causing a bug for us.

**Comment by marijnh** [comment]
Could you explain the problem a bit better? It seems in the [spec](https://www.w3.org/TR/css-values-3/#dimensions), units are simply identifiers. So I guess technically `px10px` could be tokenized as a unit here. But I don't see how that helps.

**Comment by pfaffe** [comment]
I concur, tokenizing px10px as a unit looks like a good solution. I now realize my original phrasing was a little ambiguous, I shouldn't have called it tokens. 10px10px is currently parsed as two NumberLiterals (each of which has a Unit child). Parsing as a single NumberLiteral with a Unit SGTM.

**Comment by marijnh** [comment]
I'd still like to understand the motivation behind this issue. What problem are you having with the current behavior?

**Comment by pfaffe** [comment]
`margin: 10px10px` is not a valid declaration, and per spec `10px10px` isn't two number literals with unit. The current parsing behavior makes it impossible to determine the input isn't valid.

**Comment by marijnh** [comment]
Are you using parser output for some kind of linting? Or do you mean you want the _highlighting_ to show there's something weird going on?

**Comment by pfaffe** [comment]
We're using the parser output to add decorations and UI controls to property values in DevTools (crrev.com/c/5046552).

**Comment by marijnh** [comment]
Okay. But how, specifically, is the current parsing an issue with that?

**Comment by pfaffe** [comment]
We cannot tell from the AST that the input was an invalid property declaration. We cannot validate the property value because the token sequence doesn't accurately represent the input.

**Comment by marijnh** [comment]
But does parsing this as a number with a weird unit help at all for that?

**Comment by pfaffe** [comment]
Yes, it allows us to determine that the property value's AST does not represent a valid <length>, for example. Note that we can't outright parse this as a syntax error, since something like `--var: 10px10px` is a perfectly valid declaration.

**Comment by marijnh** [comment]
That makes sense. Attached patch implements this.

**Comment by pfaffe** [comment]
Thanks a lot!
