### ISSUE TITLE
Empty value incorrectly parsed as a syntax error

### ISSUE THREAD

**Issue by pfaffe** [lezer-parser/css#13]
```* {
  --foo: ;
}
```
Is parsed as a syntax error, but this is a valid declaration. Should it be an empty-string ValueName?

**Comment by marijnh** [comment]
Oh wow, I did not know that. We could make `value` optional in the rule for `Declaration`. Would that work for you?

**Comment by pfaffe** [comment]
I could work with that. Is that easier than allowing ValueName to be empty?

**Comment by marijnh** [comment]
There's no real value name there, it's just a missing value entirely, so generating an empty node seems needlessly indirect.

Attached patch implements this.
