### ISSUE TITLE
Dialect for top level declarations (css-in-js)

### ISSUE THREAD

**Issue by Monkatraz** [lezer-parser/css#4]
Heya, at Replit we wanted to add support for CSS-in-JS, which often follows a pattern like this (example from Emotion):
```ts
import { css } from '@emotion/css'

const color = 'white'

render(
  <div
    className={css`
      padding: 32px;
      background-color: hotpink;
      font-size: 24px;
      border-radius: 4px;
      &:hover {
        color: ${color};
      }
    `}
  >
    Hover to change color.
  </div>
)
```

The `css` template string uses top level declarations, but _also_ allows nesting. We made a simple fork of the CSS grammar to support this for right now, but I suspect the best way to handle this would just be to add a dialect to the CSS grammar which allows declarations at the top level.

Our fork does this:
```
@top StyleSheet { item+ | ItemSet }
ItemSet { item* (Declaration (";" ~item item* Declaration?)*)? }
```
This was written before me, so idk the reasoning of why we did it this way, but it does seem this feature isn't hard to add, and would very helpful for us.

**Comment by Monkatraz** [comment]
That would work too.

**Comment by marijnh** [comment]
With attached patch, configuring the parser with `top: "Styles"` should allow you to parse content like this.

**Comment by Monkatraz** [comment]
Awesome, thanks!

**Comment by Kamahl19** [comment]
@Monkatraz @marijnh would you mind explaining a bit further how to allow top-level css? Thanks!

**Comment by Kamahl19** [comment]
For anyone looking for the solution

```
import { LanguageSupport } from '@codemirror/language';
import { cssCompletionSource, cssLanguage } from '@codemirror/lang-css';

const cssExtension = new LanguageSupport(
  cssLanguage.configure({ top: 'Styles' }),
  cssLanguage.data.of({ autocomplete: cssCompletionSource }),
);
```
