### ISSUE TITLE
`animation-play-state` is detected wrong

### ISSUE THREAD

**Issue by felixsanz** [lezer-parser/css#5]
If you pass to lezer this CSS:

```css
animation-direction: normal;
animation-fill-mode: none;
animation-iteration-count: 1;
animation-play-state: running;
```

All of them are `typeName` except `animation-play-state`, that is recognized wrongly as `className`

**Comment by marijnh** [comment]
When I wrap this with `div {}` and parse it, I see no `ClassName` nodes in the tree at all.

**Comment by felixsanz** [comment]
> When I wrap this with `div {}` and parse it, I see no `ClassName` nodes in the tree at all.

Yup, but don't wrap it. Imagine you're trying to highlight an example showing the usage of the CSS property, [like in this MDN article](https://developer.mozilla.org/en-US/docs/Web/CSS/animation-play-state)

![1677598047](https://user-images.githubusercontent.com/6182099/221899533-14231674-f827-4cdd-b4de-bb1066ce98e5.png)

Here you don't want to wrap it in class/element as it's irrelevant to the example.

All other CSS properties seems to work fine doing this, it's just this one that doesn't.

**Comment by marijnh** [comment]
Set the `top` parser option to `"Styles"` to parse a plain set of properties.

**Comment by felixsanz** [comment]
> Set the `top` parser option to `"Styles"` to parse a plain set of properties.

I'm having issues trying to have 2 parsers: one configured with `top` and one normal, because the `configure` method mutates the parser. I tried to clone the object using `structuredClone` but can't be cloned:

> DOMException [DataCloneError]: value => spec_callee[value] || -1 could not be cloned.

Do you know what can I do to workaround this? Thanks in advance

**Comment by felixsanz** [comment]
> Set the `top` parser option to `"Styles"` to parse a plain set of properties.

It worked in my app but I'm trying to use it in a REPL or just in a script with this lines and it fails:

```js
import { parser as cssParser } from '@lezer/css'

const cssProperties = cssParser.configure({ top: 'Styles' })
```

> RangeError: Invalid top rule name Styles
    at LRParser.configure 

What i'm doing wrong here? Thanks in advance

**Comment by marijnh** [comment]
You may be getting an older version of @lezer/css there, somehow.
