### ISSUE TITLE
Update TypeScript exports to support moduleResolution bundler

### ISSUE THREAD

**Issue by kwangure** [lezer-parser/css#7]
[`moduleResolution: "bundler"`](https://www.typescriptlang.org/tsconfig#moduleResolution) is a recent setting added to TypeScript to support bundler setups. It's the setting you should probably be using when bundling code. With this setting TypeScript only searches for types in the exports field of the `package.json`.

It requires the following change:

```diff
 "exports": {
   "import": "./dist/index.js",
   "require": "./dist/index.cjs",
+  "types": "./dist/index.d.ts"
 },
```

**Comment by marijnh** [comment]
Assuming this can also be closed (see d605916ad65eec06360a3df1b90a531d028726bc)
