### ISSUE TITLE
Tokenizing `VariableName` with escaped characters is not working

### ISSUE THREAD

**Issue by ergunsh** [lezer-parser/css#9]
Hey @marijnh,

Currently, tokenizing variable names with escape characters are not working properly.

This should tokenize correctly: `var(--\\)` as a CallExpression with VariableName that is equal to the `--\\`, according to the [spec](https://www.w3.org/TR/css-syntax-3/#consume-string-token).

We're slowly replacing our regex based parser with CodeMirror parser but this has blocked us for moving forward with replacing how we do custom property parsing. Failing test cases are [here](https://source.chromium.org/chromium/chromium/src/+/main:third_party/devtools-frontend/src/test/unittests/front_end/core/sdk/CSSMatchedStyles_test.ts;l=26?q=cssMatchedStyles_test).

WDYT, can you take a look?

**Comment by marijnh** [comment]
Attached patch should help (tagged 1.1.4).

**Comment by ergunsh** [comment]
whoa, thanks a lot for the quick fix! :)
